Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: Hand 2D Keypoint topdown_heatmap onehand10k
  Paper:
    Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/hrnetv2_onehand10k.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/hrnetv2_w18_onehand10k_256x256.py
  In Collection: Hand 2D Keypoint topdown_heatmap onehand10k
  Metadata:
    Training Data: OneHand10K
  Name: topdown_heatmap_hrnetv2_w18_onehand10k_256x256
  Results:
  - Dataset: OneHand10K
    Metrics:
      AUC: 0.568
      EPE: 24.16
      PCK@0.2: 0.99
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_onehand10k_256x256-30bc9c6b_20210330.pth
